name: FlyManager
main: de.itsuhr.Main
version: 1.0
api-version: 1.20
author: ItsUhr
description: Ein Plugin, das es Spielern ermöglicht, den Flugmodus zu aktivieren und zu steuern.
commands:
  fly:
    description: Steuert den Flugmodus und die Fluggeschwindigkeit.
    aliases: [setfly, flight, flug]
